//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int PatientsID { get; set; }
        public int DepartmentsID { get; set; }
        public int DoctorID { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime EndTime { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string ImageFile { get; set; }
        public string Image { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool Status { get; set; }
        public string Description { get; set; }
    }
}
