//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorApp.Models
{
    using System;
    
    public partial class BrowseLeaveByID_sp_Result1
    {
        public int ID { get; set; }
        public int? EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> Days { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
    }
}
