//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperienceInformation
    {
        public int ExperienceID { get; set; }
        public int DoctorID { get; set; }
        public string CompanyName { get; set; }
        public string Position { get; set; }
        public System.DateTime PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public string ExperiencePeriod { get; internal set; }
    }
}
